image: "julia"

before_script:
  - julia --version
  - apt-get update && apt-get install git -y
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lrz.de/".insteadOf "git@gitlab.lrz.de:"
  - echo $(pwd)
  - export GRB_LICENSE_FILE="$(pwd)/gurobi/gurobi.lic"

stages:          # List of stages for jobs, and their order of execution
  - test

test-job:       # This job runs in the build stage, which runs first.
  stage: test
  script:
    - julia --project=@. -e '
        using Pkg; 
        Pkg.instantiate(); 
        Pkg.build(); 
        Pkg.test(coverage=true)'
    - julia --project=@. -e '
        using Pkg; 
        Pkg.add("Coverage");
        import ScenarioSynthesis; cd(joinpath(dirname(pathof(ScenarioSynthesis)), ".."));
        using Coverage; cl, tl = get_summary(process_folder()); 
        println("Code coverage:", round(cl/tl*100; digits=2), "%")'
  coverage: '/Code coverage:\d+\.\d+/'