name = "ScenarioSynthesis"
uuid = "8735e240-8948-4952-95da-f152fe321b5a"
authors = ["Florian Finkeldei <florian.finkeldei@tum.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
